image: archlinux
packages:
  - wget
  - sudo
  - libbpf
  - bpf
  - bpftrace
sources:
  - https://github.com/jpsamaroo/BPFnative.jl
tasks:
  - setup-julia: |
      wget -q https://julialang-s3.julialang.org/bin/linux/x64/1.7/julia-1.7.1-linux-x86_64.tar.gz
      tar xf julia-1.7.1-*
      sudo ln -s $PWD/julia-1.7.1/bin/julia /usr/local/bin/julia
  - build: |
      cd BPFnative.jl
      sudo julia -e 'using Pkg; Pkg.update()' >/dev/null 2>&1
      sudo julia --project -e 'ENV["JULIA_PKG_PRECOMPILE_AUTO"]="0"; using Pkg; Pkg.instantiate()' >/dev/null 2>&1
      sudo julia --project -e 'ENV["JULIA_PKG_PRECOMPILE_AUTO"]="0"; ENV["BPFNATIVE_ROOT_TESTS"] = "1"; ENV["JULIA_DEBUG"] = "BPFnative"; using Pkg; Pkg.test("BPFnative")'
